import React from "react";

export default function PixelIcon({ name, size = 28, color = "currentColor" }) {
  const s = size;
  const cell = s / 7;
  const grids = {
    user: [
      "..XXX..",
      ".XXXXX.",
      ".XXXXX.",
      "..XXX..",
      ".XXXXX.",
      "XXXXXXX",
      "XXXXXXX",
    ],
    monitor: [
      "XXXXXXX",
      "X.....X",
      "X.....X",
      "X.....X",
      "XXXXXXX",
      "..XXX..",
      ".XXXXX.",
    ],
    briefcase: [
      "..XXX..",
      ".X...X.",
      "XXXXXXX",
      "X.....X",
      "XXXXXXX",
      "X.....X",
      "XXXXXXX",
    ],
    bolt: [
      "...XX..",
      "..XX...",
      ".XX....",
      "XXXXXX.",
      "...XX..",
      "..XX...",
      ".XX....",
    ],
    gamepad: [
      ".XX.XX.",
      "XXXXXXX",
      "X.X.X.X",
      "XXXXXXX",
      "XXXXXXX",
      ".X...X.",
      "X.....X",
    ],
    calendar: [
      "XXXXXXX",
      "X.X.X.X",
      "XXXXXXX",
      "X.....X",
      "X.X.X.X",
      "X.....X",
      "XXXXXXX",
    ],
    linkedin: [
      "XX.....",
      "XX.X.X.",
      "...X.X.",
      "..XX.X.",
      ".X.X.X.",
      "XX.X.XX",
      "...XXX.",
    ],
    github: [
      "..XXX..",
      ".XXXXX.",
      "XXXXXXX",
      "XX.X.XX",
      "XXXXXXX",
      ".X.X.X.",
      "X.....X",
    ],
    pin: [
      "..XXX..",
      ".X...X.",
      "X..X..X",
      "X.....X",
      ".X...X.",
      "..X.X..",
      "...X...",
    ],
    clock: [
      "..XXX..",
      ".X...X.",
      "X..X..X",
      "X..XX.X",
      "X.....X",
      ".X...X.",
      "..XXX..",
    ],
    mail: [
      "XXXXXXX",
      "X.....X",
      "X.X.X.X",
      "X..X..X",
      "X.....X",
      "X.....X",
      "XXXXXXX",
    ],
    robot: [
      ".XXXXX.",
      "XX.X.XX",
      "XXXXXXX",
      "X.XXX.X",
      "XXXXXXX",
      ".X...X.",
      "XX...XX",
    ],
    gear: [
      "X.X.X.X",
      ".XXXXX.",
      "XX...XX",
      "XX...XX",
      "XX...XX",
      ".XXXXX.",
      "X.X.X.X",
    ],
    home: [
      "...X...",
      "..XXX..",
      ".XXXXX.",
      "XXXXXXX",
      "X.XXX.X",
      "X.X.X.X",
      "X.XXX.X",
    ],
    close: [
      "X.....X",
      "XX...XX",
      ".XX.XX.",
      "..XXX..",
      ".XX.XX.",
      "XX...XX",
      "X.....X",
    ],
    speaker: [
      "..X....",
      ".XX.X..",
      "XXX.X.X",
      "XXX.X.X",
      "XXX.X.X",
      ".XX.X..",
      "..X....",
    ],
    arrow: [
      "...X...",
      "...XX..",
      "...XXX.",
      "XXXXXXX",
      "...XXX.",
      "...XX..",
      "...X...",
    ],
    sword: [
      "......X",
      ".....X.",
      "....X..",
      "...X...",
      "..X.X..",
      ".X...X.",
      "X.....X",
    ],
    shield: [
      ".XXXXX.",
      "XXXXXXX",
      "XX.X.XX",
      "XX.X.XX",
      ".XXXXX.",
      "..XXX..",
      "...X...",
    ],
    star: [
      "...X...",
      "...X...",
      "XXXXXXX",
      ".XXXXX.",
      "..X.X..",
      ".X...X.",
      "X.....X",
    ],
    heart: [
      ".XX.XX.",
      "XXXXXXX",
      "XXXXXXX",
      "XXXXXXX",
      ".XXXXX.",
      "..XXX..",
      "...X...",
    ],
    map: [
      "X..X..X",
      "X..X..X",
      "XXXXXXX",
      "X..X..X",
      "X..X..X",
      "X..X..X",
      "XXXXXXX",
    ],
    scroll: [
      "XXXXXXX",
      "X.....X",
      "X.XXX.X",
      "X.XXX.X",
      "X.XXX.X",
      "X.....X",
      "XXXXXXX",
    ],
  };
  const grid = grids[name] || grids.gear;
  return (
    <svg width={s} height={s} viewBox={`0 0 ${s} ${s}`} style={{ imageRendering: "pixelated", display: "block" }}>
      {grid.map((row, y) =>
        row.split("").map((c, x) =>
          c === "X" ? (
            <rect key={`${x}-${y}`} x={x * cell} y={y * cell} width={cell + 0.5} height={cell + 0.5} fill={color} />
          ) : null
        )
      )}
    </svg>
  );
}
